version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthleap-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Si necesitas Redis para almacenamiento de tokens o rate limiting
  redis:
    image: redis:6-alpine
    container_name: healthleap-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: